### ISSUE TITLE
B Block Data Exercise

### ISSUE THREAD

**Issue by datapolitan** [Datapolitan-Training/parks-excel-analysis-ii#13]
@lizdumont I'm not sure the exercise "Is There a Correlation Between the # of Inspections and the # of Hours Worked?" is a good one to get them reacquainted with the data for several reasons:
1. It implies they already understand correlations, a topic we haven't covered
2. It is an involved process to get the answer, which could lead people to check-out. One of our cherished design patterns is the mastery exercise to get them started and confident before we throw too many complications at them. Each twist is a point of friction in which their attention could easily break.
3. I'm not certain what the outcome is. I think it's important to point out that PIP inspections are done every 6 months and generally don't vary. Supervisor inspections happen more frequently and can vary.

**Comment by lizdumont** [comment]
I can change correlation to relationship.

As for the exercise, this was a day process for Mark to find a way to incorporate SUMIF and COUNTIF in the class in a way that is meaningful. Any other use we came up with can be done easier and better with a PivotTable. I agree that it is intricate, but this was the best that we came up with. I'm not sure how to move forward.
