### ISSUE TITLE
Pull list of "Key Elements to Consider When Designing a Visual" from beginning

### ISSUE THREAD

**Issue by datapolitan** [Datapolitan-Training/parks-excel-analysis-ii#17]
Recap at end of section (i.e. after "Data-Ink Ratio")

**Comment by lizdumont** [comment]
I took this format from the 5 tasks in Excel. I think it's good pedagogy to prep for what will be learned before going through each. I can add another recap slide with the list if you'd like. I'm curious why you think it's important to pull it.
