### ISSUE TITLE
Walk-through Images are too Small

### ISSUE THREAD

**Issue by datapolitan** [Datapolitan-Training/parks-excel-analysis-ii#22]
Think about using the `[img-right-40]` or other tags to move the images to the sides and make them bigger so they can be seen. Right now, they're on the bottom and too small to make out.

**Comment by lizdumont** [comment]
Sorry - which slide(s) are you referring to?

**Comment by datapolitan** [comment]
The "boro" example with `SUMIF` and `COUNTIF`. I know these are going to change, but just keep it in mind that you can display images on the sides or even the top and not have to put it just at the bottom. Also, you can play with the sizing so long as the size you want is defined in the `slide.css`

**Comment by datapolitan** [comment]
I think we got them all
