### ISSUE TITLE
Add rough datasets to data folder as placeholder

### ISSUE THREAD

**Issue by datapolitan** [Datapolitan-Training/parks-excel-analysis-ii#24]
Make sure the datasets we're using are in the repo and available for students.

**Comment by lizdumont** [comment]
They will be after the 31st. I've arranged with Dennis to have him pull January 1st to March 31st so we have the most up-to-date data.

**Comment by datapolitan** [comment]
@lizdumont thanks for putting the data we have so the client can see. See #42 for the updated datasets for class
