### ISSUE TITLE
Slides 173, 177, and 180

### ISSUE THREAD

**Issue by lizdumont** [Datapolitan-Training/parks-excel-analysis-ii#27]
Remove the -- for the first line of information.

**Comment by datapolitan** [comment]
@lizdumont Your numbering is going to change because of edits. I'd reference these more explicitly using the `name:` attribute

**Comment by datapolitan** [comment]
@lizdumont And I usually like having the header display to intro the topic before getting into the bullets. Just a suggestion

**Comment by lizdumont** [comment]
@datapolitan it's the second, third, and fourth time we use the header and creates annoying extra clicks.
