### ISSUE TITLE
Break between Short Boro and Full Boro

### ISSUE THREAD

**Issue by datapolitan** [Datapolitan-Training/parks-excel-analysis-ii#37]
The purpose of this is to:
1. Show the result of which boro has the most inspections from [Short Boro](http://training.datapolitan.com/parks-excel-analysis-ii/#short-boro) 
2. Give time for students to catch up and learning to integrate before moving on
3. Demonstrate editing in PivotTable for values
4. Set up for [Full Boro](http://training.datapolitan.com/parks-excel-analysis-ii/#full-boro) with the question -> "what if we want the full boro name in a column of our data?"

The reason for this is to manage the flow of information to students to prevent oversaturation, particularly this early in the class.

**Comment by lizdumont** [comment]
@datapolitan What edits are you looking for here? An extra slide to remind us to pause and ask for questions before we teach the next piece?

**Comment by lizdumont** [comment]
@datapolitan Apologies but I'm confused - are you wanting to move the 15 minute break here, or are you wanting us to build in a pause to debrief LEFT before moving on to IF?

**Comment by datapolitan** [comment]
@lizdumont A pause to cement the learning before moving to the next topic. If it makes sense for a break here (referenced #29) then that's fine. We'll need to figure out the timing but I just don't think we should rush from short boro to full boro without making it clear what we're doing and why.

**Comment by datapolitan** [comment]
Also, a chance to review refreshing a pivottable
