### ISSUE TITLE
Fix Full Boro Formula

### ISSUE THREAD

**Issue by datapolitan** [Datapolitan-Training/parks-excel-analysis-ii#38]
I don't think it's a good practice to teach a dangling False in the IF statement. In this case, we assumed anything that doesn't match the other four boros is Staten Island. This may be the case in this dataset, but it's possible this isn't true and it's better to teach an explicit handling of cases that don't exactly match. 

In other words:
```
=IF(B4="B","Brooklyn",IF(B4="Q","Queens",IF(B4="M","Manhattan",IF(B4="X","Bronx",IF(B4="R","Staten Island","Other")))))
```

**Comment by lizdumont** [comment]
@datapolitan completely fair. I'll edit with "Other" as the final FALSE.
