### ISSUE TITLE
Conditional Formulas vs Logical Functions

### ISSUE THREAD

**Issue by datapolitan** [Datapolitan-Training/parks-excel-analysis-ii#39]
I hate to nitpick this, but conditional formulas leverage logical functions. `IF` is a logical function, not a conditional formula. A conditional formula can use IF, as well as the other logical functions you list as conditional formulas.

I'd just like the language to be clear, concise, and accurate. We need to describe conditional formulas and logical formulas in a way that makes this difference clear

**Comment by lizdumont** [comment]
@datapolitan 
This is a great "nitpick", honestly. I wasn't clear on the difference based on what I read online. See what you think of the edits I made.

**Comment by datapolitan** [comment]
@lizdumont I think this is good, but you also confuse nested formulas with a conditional formula. Not all conditional formulas are nested, nor are all nested formulas conditional formulas. 
+ **Nesting** is a technique to use the return from one function as an input into another
+ **Conditional formulas** vary the output by the type of input

**Comment by datapolitan** [comment]
@lizdumont I made edits and restructured the exercise to draw out these distinctions, including leveraging #40 and #41
