### ISSUE TITLE
Demo conditional logic

### ISSUE THREAD

**Issue by datapolitan** [Datapolitan-Training/parks-excel-analysis-ii#41]
This one is tricky, but I think doing something on a conditional logic would be good to reinforce learning. 

My suggestion is to use a `LEFT`/`MID`/`RIGHT` that uses `FIND` as an input to a start [like this example](https://exceljet.net/formula/get-first-name-from-name-with-comma)
This could be in the PIP data, in the Daily Tasks, or in the 311. Unfortunately, 311 offers some great examples of this (split on the LOCATION column or on COMMUNITY BOARD column)

**Comment by lizdumont** [comment]
@datapolitan Are you wanting to reinforce nesting in order to create a conditional formulas?  Or could we use COUNTIF as the reinforcement? We could do a COUNTIF of how many "A" ratings the park got for the inspection. This would give them an extra line of data that they could compare over time.

**Comment by lizdumont** [comment]
@datapolitan  we could also do nested =COUNT(IF()) and then reveal COUNTIF as a way of saving a heck of a lot of typing....

**Comment by lizdumont** [comment]
@datapolitan  Did some playing around with the order of the slides now that you have made the distinction for me of logical function vs conditional formulas. I think the reorganizing answers your desire for a reinforcement. Let me know if this works for you. This should also answer issues #36 and #39 .

**Comment by datapolitan** [comment]
@lizdumont See the additional exercise to test whether an inspection happened in the morning or the afternoon. Apparently the PIP folk are morning people. 

![tod3](https://user-images.githubusercontent.com/7535465/55308338-0faa0c80-5420-11e9-934f-a360f72e69fd.png)
