### ISSUE TITLE
Broken link on slide 261 ("Data Sensemaking")

### ISSUE THREAD

**Issue by dennisrim** [Datapolitan-Training/parks-excel-analysis-ii#56]
FYI - the "Data Sensemaking by Enrico Bertini" link is broken. Rather, it seems that the website no longer exists. See attached screenshot.

![image](https://user-images.githubusercontent.com/45013273/55508772-90d3f000-5628-11e9-9c1b-6696fe299a4d.png)

**Comment by datapolitan** [comment]
Thanks @dennisrim for the comment. We'll get this fixed

**Comment by datapolitan** [comment]
Messaged Enrico to ask about him reposting on Medium.
